config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq' # mount Sidekiq::Web in your Rails app

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'root#index'

  resources :talents do
    resources :streaming_platforms
    resources :streamers, only: %i[new create edit update destroy]
  end

  resources :streamings, only: %i[destroy]
end

app/models/streamer.rb
class Streamer < ApplicationRecord
  belongs_to :talent
  belongs_to :streaming_platform
  has_many :streamings, dependent: :destroy

  before_validation :normalize_streamer_key

  def url
    "#{streaming_platform.url}/#{streamer_key}"
  end

  def action_if_streaming
    fetched_streaming = streaming_platform.fetch_streaming(url)
    return unless fetched_streaming.streaming?

    streaming = streamings.find_or_initialize_by(unique_key: fetched_streaming.unique_key).tap do |s|
      s.start_at = fetched_streaming.start_at
      s.title = fetched_streaming.title
    end
    return if streaming.persisted?

    streaming.save!
    streaming.action_after_create
  end

  private

  def normalize_streamer_key
    self.streamer_key = streamer_key.remove(%r{/$}) if streamer_key.present?
  end
end

app/controllers/streamers_controller.rb
class StreamersController < ApplicationController
  def new
    @talent = Talent.find(params[:talent_id])
    @streamer = @talent.streamers.new
  end

  def create
    @talent = Talent.find(params[:talent_id])
    @streamer = @talent.streamers.new(streamer_params)
    if @streamer.save
      redirect_to root_path, notice: 'Streamer was successfully created.'
    else
      render :new
    end
  end

  def edit
    @talent = Talent.find(params[:talent_id])
    @streamer = @talent.streamers.find(params[:id])
  end

  def update
    @talent = Talent.find(params[:talent_id])
    @streamer = @talent.streamers.find(params[:id])
    if @streamer.update(streamer_params)
      redirect_to root_path, notice: 'Streamer was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @talent = Talent.find(params[:talent_id])
    @streamer = @talent.streamers.find(params[:id])
    @streamer.destroy
    redirect_to root_path, notice: 'Streamer was successfully destroyed.'
  end

  private

  def streamer_params
    params.require(:streamer).permit(:streamer_key, :streaming_platform_id, :notify, :download_live_stream)
  end

  def available_streaming_platforms
    StreamingPlatform.all
  end

  helper_method :available_streaming_platforms
end

app/views/streamers/_form.html.erb
<%= form_with model: [talent, streamer], local: true do |form| %>
  <% if form.object.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(form.object.errors.count, "error") %> prohibited this streamer from being saved:</h2>
      <ul>
        <% @streamer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :streaming_platform_id, "ストリームプラットフォーム" %>
    <% if streamer.new_record? %>
    <%= form.select :streaming_platform_id, available_streaming_platforms.map { |sp| [sp.name, sp.id] } %>
    <% else %>
      <%= form.object.streaming_platform.name %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :streamer_key, "Streamer Key" %>
    <%= form.text_field :streamer_key %>
  </div>

  <div class="field">
    <%= form.label :notify, "通知" %>
    <%= form.check_box :notify %>
  </div>

  <div class="field">
    <%= form.label :download_live_stream, "Download Live Stream" %>
    <%= form.check_box :download_live_stream %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/streamers/edit.html.erb
<h1><%= @talent.name %>のストリーマー編集</h1>
<%= link_to '削除する', talent_streamer_path(@talent, @streamer), method: :delete, data: { confirm: '本当に削除しますか？' } %>

<%= render 'form', talent: @talent, streamer: @streamer %>

app/views/streamers/new.html.erb
<h1><%= @talent.name %>のストリーマー新規登録</h1>

<%= render 'form', talent: @talent, streamer: @streamer %>