config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq' # mount Sidekiq::Web in your Rails app

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'root#index'

  resources :talents do
    resources :streaming_platforms
    resources :streamers, only: %i[new create edit update destroy]
  end

  resources :streamings, only: %i[destroy]
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
    @streamers = Streamer.eager_load(:talent, :streaming_platform).group_by(&:talent)
    @streamings = Streaming.order(start_at: :desc).eager_load(streamer: :talent,
                                                              movie_attachment: :blob).with_attached_movie
  end
end

app/views/root/index.html.erb
<h1>登録しているストリーマー</h1>
<% @streamers.each do |talent, streamers| %>
  <h2><%= talent.name %></h2>
  <%= link_to '配信サイトを追加する', new_talent_streamer_path(talent) %>

  <table border="1">
    <tr>
      <th>name</th>
      <th></th>
    </tr>

    <% streamers.each do |streamer| %>
      <tr>
        <td>
          <%= streamer.streaming_platform.name %><br>
          <%= link_to '編集', edit_talent_streamer_path(talent, streamer) %>
        </td>
        <td>
          <ul>
            <li>url: <%= link_to streamer.streamer_key, streamer.url if streamer.streamer_key.present? %></li>
            <li>notify: <%= streamer.notify ? 'ON' : 'OFF' %></li>
            <li>download_streaming: <%= streamer.download_live_stream ? 'ON' : 'OFF' %></li>
          </ul>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

<h1>取得したライブ配信一覧</h1>

<table border="1">
  <tr>
    <th>タイトル</th>
    <th>開始日時</th>
    <th>ストリーマー</th>
    <th></th>
    <th>ステータス</th>
    <th></th>
  </tr>

  <% @streamings.each do |streaming| %>
    <tr>
      <td><%= streaming.title %></td>
      <td><%= streaming.start_at %></td>
      <td><%= streaming.streamer.talent.name %></td>
      <td>
        <% if streaming.movie.attached? %>
          <%= link_to 'ダウンロード', rails_blob_url(streaming.movie, disposition: 'attachment') %>
        <% end %>
      </td>
      <td><%= streaming.status %></td>
      <td><%= link_to '削除する', streaming_path(streaming), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>